language: android
jdk: oraclejdk8
sudo: false

android:
 components:
  - platform-tools
  - tools
#  - build-tools-21.1.2
#  - build-tools-23.0.3
#  - build-tools-25.0.0
#  - build-tools-25.0.3
  - build-tools-26.0.2
  - android-19 #Minimum API Version
#  - android-21
  - android-23 #Target API Version
#  - android-26 #Newest API Version
  #- sys-img-armeabi-v7a-android-21
  #- extra-android-m2repository

#script:
# - gradle assemble

notifications:
 slack: technoramic5190:DzHEyly89iwtuHPp933y0cNE
#
#  before_script:
#          #create and start emulator
#          - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#          - emulator -avd test -no-skin -no-audio -no-window &
#          - android-wait-for-emulator
#          - adb shell input keyevent 82 &
#
